.PHONY 	all \
	setup \
	run

venv/bin/activate:
	python3 -m venv venv

setup:
	venv/bin/activate
	venv/bin/activate; pip install pip wheel setuptools
	venv/bin/activate; pip install -r requirements.txt

run:
	venv/bin/activate
	venv/bin/activate; python main.py
